local _, kyleUI = ...
local m = kyleUI:CreateModule("omnibar")

local eventHandler = CreateFrame("Frame", nil, UIParent)
eventHandler:SetScript(
    "OnEvent",
    function(self, event, ...)
        return self[event](self, ...)
    end
)

function m:Setup(addonProfileKey)
    if OmniBarDB["profiles"][addonProfileKey] == nil then
        OmniBarDB["profiles"][addonProfileKey] = {
            ["bars"] = {
                ["OmniBar2"] = {
                    ["glow"] = true,
                    ["noDefault"] = true,
                    ["tooltips"] = true,
                    ["multiple"] = true,
                    ["center"] = true,
                    ["swipeAlpha"] = 0.65,
                    ["size"] = 40,
                    ["cooldownCount"] = true,
                    ["ratedBattleground"] = false,
                    ["unusedAlpha"] = 0.45,
                    ["align"] = "CENTER",
                    ["spell47528"] = false,
                    ["maxIcons"] = 500,
                    ["name"] = "Defensives",
                    ["position"] = {
                        ["relativeTo"] = "UIParent",
                        ["point"] = "CENTER",
                        ["relativePoint"] = "CENTER",
                        ["yOfs"] = -143.0120849609375,
                        ["xOfs"] = 0,
                        ["frameStrata"] = "MEDIUM"
                    },
                    ["spell212800"] = true,
                    ["arena"] = true,
                    ["spell48707"] = true,
                    ["scenario"] = false,
                    ["spell31224"] = true,
                    ["border"] = true,
                    ["names"] = false,
                    ["spell22812"] = true,
                    ["spell47585"] = true,
                    ["growUpward"] = true,
                    ["spell104773"] = true,
                    ["spell108271"] = true,
                    ["world"] = false,
                    ["spell51052"] = true,
                    ["highlightTarget"] = true,
                    ["columns"] = 20,
                    ["spell205604"] = true,
                    ["spell33206"] = true,
                    ["spell210256"] = true,
                    ["adaptive"] = true,
                    ["spell6940"] = true,
                    ["spell116849"] = true,
                    ["spell122470"] = true,
                    ["spell102342"] = true,
                    ["showUnused"] = true,
                    ["highlightFocus"] = false,
                    ["padding"] = 2,
                    ["locked"] = true,
                    ["battleground"] = false
                },
                ["OmniBar5"] = {
                    ["spell408"] = true,
                    ["glow"] = true,
                    ["noDefault"] = true,
                    ["tooltips"] = true,
                    ["spell80240"] = true,
                    ["multiple"] = true,
                    ["spell853"] = true,
                    ["highlightFocus"] = false,
                    ["spell5246"] = true,
                    ["swipeAlpha"] = 0.65,
                    ["spell221562"] = true,
                    ["size"] = 40,
                    ["cooldownCount"] = true,
                    ["ratedBattleground"] = false,
                    ["spell107570"] = true,
                    ["unusedAlpha"] = 0.45,
                    ["align"] = "RIGHT",
                    ["maxIcons"] = 500,
                    ["name"] = "CC",
                    ["position"] = {
                        ["relativeTo"] = "UIParent",
                        ["point"] = "CENTER",
                        ["relativePoint"] = "CENTER",
                        ["yOfs"] = -46.6172981262207,
                        ["xOfs"] = -154.0746002197266,
                        ["frameStrata"] = "MEDIUM"
                    },
                    ["arena"] = true,
                    ["spell2094"] = true,
                    ["scenario"] = false,
                    ["border"] = true,
                    ["names"] = false,
                    ["spell119381"] = true,
                    ["growUpward"] = true,
                    ["spell204437"] = true,
                    ["spell211881"] = true,
                    ["world"] = false,
                    ["highlightTarget"] = true,
                    ["columns"] = 20,
                    ["spell5211"] = true,
                    ["spell15487"] = true,
                    ["spell64044"] = true,
                    ["spell6789"] = true,
                    ["adaptive"] = true,
                    ["spell187650"] = true,
                    ["spell8122"] = true,
                    ["spell179057"] = true,
                    ["center"] = false,
                    ["locked"] = true,
                    ["padding"] = 2,
                    ["showUnused"] = true,
                    ["battleground"] = false
                },
                ["OmniBar1"] = {
                    ["glow"] = true,
                    ["scenario"] = false,
                    ["border"] = true,
                    ["tooltips"] = true,
                    ["names"] = false,
                    ["multiple"] = true,
                    ["highlightFocus"] = false,
                    ["growUpward"] = false,
                    ["arena"] = true,
                    ["locked"] = true,
                    ["highlightTarget"] = true,
                    ["position"] = {
                        ["relativeTo"] = "UIParent",
                        ["point"] = "CENTER",
                        ["relativePoint"] = "CENTER",
                        ["yOfs"] = -183.6007385253906,
                        ["xOfs"] = 0,
                        ["frameStrata"] = "MEDIUM"
                    },
                    ["world"] = false,
                    ["cooldownCount"] = true,
                    ["ratedBattleground"] = true,
                    ["columns"] = 20,
                    ["unusedAlpha"] = 0.45,
                    ["align"] = "CENTER",
                    ["size"] = 40,
                    ["swipeAlpha"] = 0.65,
                    ["adaptive"] = true,
                    ["maxIcons"] = 500,
                    ["showUnused"] = true,
                    ["name"] = "Interrupts",
                    ["spell31935"] = false,
                    ["spell212619"] = true,
                    ["padding"] = 2,
                    ["center"] = true,
                    ["battleground"] = false
                },
                ["OmniBar3"] = {
                    ["glow"] = true,
                    ["noDefault"] = true,
                    ["tooltips"] = true,
                    ["multiple"] = true,
                    ["spell121471"] = true,
                    ["center"] = false,
                    ["swipeAlpha"] = 0.65,
                    ["spell197871"] = true,
                    ["size"] = 40,
                    ["cooldownCount"] = true,
                    ["ratedBattleground"] = false,
                    ["unusedAlpha"] = 0.45,
                    ["align"] = "RIGHT",
                    ["maxIcons"] = 500,
                    ["name"] = "Offensives",
                    ["position"] = {
                        ["relativeTo"] = "UIParent",
                        ["point"] = "CENTER",
                        ["relativePoint"] = "CENTER",
                        ["yOfs"] = -95.60490417480469,
                        ["xOfs"] = -154.0736236572266,
                        ["frameStrata"] = "MEDIUM"
                    },
                    ["arena"] = true,
                    ["scenario"] = false,
                    ["spell190319"] = true,
                    ["border"] = true,
                    ["names"] = false,
                    ["growUpward"] = true,
                    ["spell31884"] = true,
                    ["world"] = false,
                    ["highlightTarget"] = true,
                    ["columns"] = 15,
                    ["spell185313"] = true,
                    ["spell113858"] = true,
                    ["spell2825"] = true,
                    ["spell167105"] = true,
                    ["adaptive"] = true,
                    ["spell102560"] = true,
                    ["spell79140"] = true,
                    ["spell204160"] = true,
                    ["highlightFocus"] = false,
                    ["locked"] = true,
                    ["padding"] = 2,
                    ["showUnused"] = true,
                    ["battleground"] = false
                }
            }
        }
        print("kyleUI profile installed for OmniBar")
    end
end
